[build]
  command = "pnpm build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  PNPM_VERSION = "9"

[[redirects]]
  from = "/api/swagger/*"
  to = "https://develop.lokit.co.kr/api/swagger/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/api/swagger"
  to = "https://develop.lokit.co.kr/api/swagger"
  status = 302
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://develop.lokit.co.kr/api/:splat"
  status = 200
  force = true